name: Java CI (1.20.1 Fabric)

on:
  push:
    branches:
      - '2001/fabric'
  workflow_dispatch:
    branches:
      - '2001/fabric'
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        default: 'release'
        options:
          - 'release'
          - 'beta'
          - 'alpha'
          - 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Move builds
        run: |
          mv build/libs/kubejs-create-fabric-2001.2.5-build.{{ github.run_number }}.jar build/libs/kjs-build.jar
      - uses: mmkal/artifact.ci/upload@main
        with:
          path: build/libs/kjs-build.jar
          artifactci-visibility: public
          artifactci-mode: eager
